name: media_notification
description: Flutter media notification
version: 0.0.5
author: Dmitry <dima.potapov.98@mail.ru>
homepage: https://github.com/Zeratyll/flutter_media_notification

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.0.4
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito:
  
# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.example.medianotification
    pluginClass: MediaNotificationPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"